apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: lohith-9Hi/${{values.name}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
